version: '3.8'
services:
  elasticsearch:
    container_name: elasticsearch
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    image: 'docker.elastic.co/elasticsearch/elasticsearch:7.17.0'
    networks:
      - elastic

  kibana:
    container_name: kibana
    ports:
      - '5601:5601'
    environment:
      - 'ELASTICSEARCH_HOSTS=http://elasticsearch:9200'   
    image: 'docker.elastic.co/kibana/kibana:7.17.0'   
    healthcheck:
      test: ["CMD", "curl", "-f", "kibana:5601"]
      interval: 50s
      timeout: 50s
      retries: 5
    depends_on:
      - elasticsearch
    networks:
      - elastic 

  fluentd:
    build: ./fluentd
    container_name: fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"            
    networks:
      - elastic 

networks:
  elastic:
    name: elastic